name: solva_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  go_router: ^14.2.3
  surf_lint_rules: ^3.1.0
  bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_animate: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: BadComic
      fonts:
        - asset: assets/fonts/Bad-Comic.ttf
